[program:notification-consumer]
command=python kafka_consumer.py
directory=d:\面试\worker
autostart=true
autorestart=true
startretries=10
user=root
stdout_logfile=d:\面试\worker\logs\consumer.log
stderr_logfile=d:\面试\worker\logs\consumer_error.log
stdout_logfile_maxbytes=50MB
stdout_logfile_backups=10
environment=PYTHONPATH="d:\面试\worker"
